/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n7.1.3-34-g09dc319bf3-20260119"
#endif /* AVUTIL_FFVERSION_H */
